apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Exposes React on Minikube at http://localhost:30000

---
apiVersion: v1
kind: Service
metadata:
  name: php-backend-service
spec:
  selector:
    app: php-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

